config:
    dev:
        name: development
        db_driver: postgres
        db_source: postgresql://root:secret@localhost:5432/posada?sslmode=disable
        migration_url: file://db/migration
        http_server_address: 0.0.0.0:8080
        http_redis_address: 0.0.0.0:6379
        access_token_duration: 15m
        refresh_token_duration: 24h
        token_symmetric_key: 12345678901234567890123456789012
        default_role_external_id: URE102
    test:
        name: test
        db_driver: postgres
        db_source: postgresql://root:secret@localhost:5432/posada?sslmode=disable
        migration_url: file://db/migration
        http_server_address: 0.0.0.0:8080
        http_redis_address: 0.0.0.0:6379
        access_token_duration: 15m
        refresh_token_duration: 24h
        token_symmetric_key: 12345678901234567890123456789012
        default_role_external_id: URE102
    prod:
        name: production
        db_driver: postgres
        db_source: postgresql://root:secret@localhost:5432/posada?sslmode=disable
        migration_url: file://db/migration
        http_server_address: 0.0.0.0:8080
        http_redis_address: 0.0.0.0:6379
        access_token_duration: 15m
        refresh_token_duration: 24h
        token_symmetric_key: 12345678901234567890123456789012
        default_role_external_id: URE102