version: "3.9"
services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=posada
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - POSADA_ENV=prod
    depends_on:
      postgres:
        condition: service_healthy
    command: [ "/app/main" ]